### ISSUE TITLE
Evidence in Institution/Installation

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#12]
On second thought, we don't need the differentiation between textual and material evidence. What we do need is a way to add extra references to that (after all: many institutions/installations will be mentioned in more than one source, and we need to be able to trace all of those references). So maybe just a + or 'add'-button?

**Comment by Kandroodi** [comment]
EvidenceInstitutionRelation and EvidenceInstallationRelation are already exist. In the new implementation of forms, it will be easy working with them.
