### ISSUE TITLE
have as few things set to obligatory as possible / have neutral options for dropdown menus

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#17]
A lot of things are currently set to obligatory. Similarly, not all dropdown options have a neutral option (e.g. Bibliography does not have that under Water System). In many cases, however, we will not have all data (and presumably many of our finds will not actually have been mentioned in books or articles before). So it would be best to have as few things set to obligatory as possible, ideally none (I don't think we would have a massive problem with empty entries or something like that, as we're only five people using it)

**Comment by Kandroodi** [comment]
I reduced the obligatory fields to only essential ones.
