### ISSUE TITLE
autocomplete instead of dropdown??

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#18]
At some point, we will have a rather large number of sources (possibly hundreds). A dropdown menu would then be rather inconvenient. Is is possible to exchange it for a autocomplete method, so that - for instance - when I type 'ibn k' it will give me 'ibn kathir', 'ibn khallikan', etc.? That would have to recognise the transliteration system I sent you earlier, so that when I type 'ibn battu' it should give me 'Ibn Baṭṭūṭa'.

**Comment by Kandroodi** [comment]
It is done.
