### ISSUE TITLE
Traffic light with two status (Orange: not completed entry and, Green: Completed)

### ISSUE THREAD

**Issue by Kandroodi** [Kandroodi/WaterSystem#20]
The user will decide about the status. So, it should be a required field. (It is not with high priority for now).

**Comment by josephinevdbent** [comment]
It is currently a required field, but that means we can only save it if we check it as 'completed'. So the system of having the option of indicating that something is not complete does not seem to work right now.

**Comment by josephinevdbent** [comment]
By the way, can we also have the 'traffic light' for 'Institution' and 'Person'?

**Comment by Kandroodi** [comment]
The status field is not a required field, now. I'm going to add traffic lights for "Person", "Evidence" and "Secondary literature" as we discussed during the meeting.

**Comment by josephinevdbent** [comment]
Perfect, thank you!

**Comment by Kandroodi** [comment]
It is done.
