### ISSUE TITLE
The order of items in the Add/View tab should be according to the following list:

### ISSUE THREAD

**Issue by Kandroodi** [Kandroodi/WaterSystem#22]
o	Installation
o	Institution 
o	Person
o	Purpose
o	Role 
o	Institution type
o	Water system
o	Neighbourhood
o	City
o	Religion
o	Evidence 
o	Secondary literature

**Comment by josephinevdbent** [comment]
I wrote this list when we still thought that 'Evidence' and 'Secondary literature' would be linked to Zotero. So it should be slightly altered, to this: 

o Installation
o Institution
o Person
o Evidence
o Secondary literature
----------------------------------------
o Purpose
o Role
o Institution type
o Water system
o Neighbourhood
o City
o Religion

The things below the line are the things that should only be able to be added to by one of us (i.e., by me).
