### ISSUE TITLE
Add Evidence Date Field

### ISSUE THREAD

**Issue by Peter-J-B** [Kandroodi/WaterSystem#37]
When adding 'Evidence' the date must be given in the format YYYY-MM-DD. If you only put in the year (YYYY) and then click on save, nothing is saved. There is no error message to tell you to correct the date format or that saving has been unsuccessful. This could lead to people thinking they have correctly saved the 'evidence' without anything appearing in the database.

**Comment by Kandroodi** [comment]
It is done.
