### ISSUE TITLE
Installation Location Field

### ISSUE THREAD

**Issue by Peter-J-B** [Kandroodi/WaterSystem#38]
When adding 'installations' there is an option for selecting 'location'. I cannot find how to add locations so that these can be assigned to installations.

**Comment by Kandroodi** [comment]
In order to add a new location, you can use the plus sign on the right side of the field. At the moment It's not in the Add drop-down tab. If it is not convenient I can add it to the Add drop-down tab as well.

**Comment by Kandroodi** [comment]
Locations can be added from the drop-down menu as well.
