### ISSUE TITLE
day/month should not be obligatory [bug/enhancement]

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#43]
dates currently require a day and month (and then also give a time).
We don't need that, as in most cases we don't know it. I think we talked in the past about allowing all these options:

day 1999-12-04 Y-M-D
month 1999-12 Y-M
year 1999y y
decade 200d d 1990-2000
century 20c c 1900-2000
millennium 2m m 1000-2000

**Comment by Kandroodi** [comment]
Day or month in the date fields is not obligatory. 
For the year e.g. 1992, you can enter 1992 or 1992y.
if it is not working in a specific form, please let e know.
