### ISSUE TITLE
diacritics are not working well [bug]

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#44]
Diacritics can be entered, but they are not properly searchable. E.g. typing in 'nas' will give you 'Al-Nasir Muhammad ibn Qalawun' (which has been entered without diacritics) but not 'al-Nāṣir'.

**Comment by josephinevdbent** [comment]
As we're starting to use the database, it would be great if this could be resolved fairly soon :)

**Comment by Kandroodi** [comment]
Diacritics work well for searches (in the form fields and simple search). let me know if there is any case that it isn't working.

**Comment by josephinevdbent** [comment]
Thank you so much! I'll let you know if there are any problems (although pretty much everyone is on holiday right now, so it'll probably a couple of weeks before potential issues are discovered). Have a good summer!
