### ISSUE TITLE
person cannot be deleted [bug]

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#50]
At the moment, when a person has been added to an installation/institution, they cannot be removed. They can be changed, but if you made a mistake, they cannot be removed.

**Comment by Kandroodi** [comment]
If you tick the small square in the last column, under the red cross, then hit the save, it will be removed.

**Comment by josephinevdbent** [comment]
Thanks Mojtaba! I noticed you did quite some work on it in the past couple of days. I am going on break now, but I'll be back on January 4, when looking at the database is the first thing on my list.


Happy holidays!


all best, Josephine


________________________________
Van: Kandroodi <notifications@github.com>
Verzonden: woensdag 23 december 2020 14:09
Aan: Kandroodi/WaterSystem
CC: Bent, J.M.C. van den (Josephine); Author
Onderwerp: Re: [Kandroodi/WaterSystem] person cannot be deleted [bug] (#50)


If you tick the small square in the last column, under the red cross, then hit the save, it will be removed.

-

**Comment by Kandroodi** [comment]
Dear Josephine,


I was trying to get things done as much as possible before the holidays but I don't need any urgent feedback from you.

Have great holidays and a happy new year!
Mojtaba?


________________________________
