### ISSUE TITLE
! institution as location [enhancement] 

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#58]
We should be able to locate installations within an institution. 
E.g.: a fountain is in a mosque. Then we don't want to give the specific location for the water installation itself, because than it will appear as if it is and independent thing that just happens to be in the same place as the mosque (if we know exactly where it is) or just in the same neighbourhood (if we only have a vague idea of its location). So in order to make sure it is *in* the mosque, we need to be able to have that as a location.

(the connection to institution at the bottom is not sufficient for this)

**Comment by Kandroodi** [comment]
It is done.
