### ISSUE TITLE
new neighbourhood closes tab [bug]

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#66]
When we make a new neighbourhood, saving it gives odd results, mostly it refers you to a blank page. The neighbourhood is still saved, so it's not a major problem at the moment, but it is a bit odd.

**Comment by Kandroodi** [comment]
The bug is not clear. Please check it again and if the bug is still there, add a screenshot of it to make it clear.

**Comment by Kandroodi** [comment]
Bug fixed.
