### ISSUE TITLE
! installation and institution need an alphanumeric code [enhancement]

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#67]
Because in many cases installations (e.g. 'waterwheel' or 'aqueduct') or institutions (e.g. 'mosque') don't have a proper name to differentiate them from similar installations/institutions, we would like each entry into these two categories to have an automated alphanumeric code.

**Comment by Kandroodi** [comment]
It is done.

**Comment by josephinevdbent** [comment]
Thanks for adding this! But can you please make it so that the code and name are separate. So we can enter the name as we like, and then there is a code attached to the whole thing that is in another field (also so we can't accidentally delete the code).
