### ISSUE TITLE
Uploading 'shapefile' when creating/editing 'Neighbourhood'

### ISSUE THREAD

**Issue by Peter-J-B** [Kandroodi/WaterSystem#75]
When creating/editing 'Neighbourhood', I am not sure if 'shapefiles' can be attached, as, currently, there does not seem to be any record of attached files after the record is saved - maybe this is something that is not ready at this stage?

If not, can we go ahead and create database entries which link to a specific neighbourhood and then attach the 'shapefile' later when this feature is ready?

Thanks,
Peter

**Comment by Kandroodi** [comment]
It is done.
