### ISSUE TITLE
Please make the box ‘description’ bigger under ‘evidences’

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#81]
Because some of the quotes are pretty lengthy and the single row makes it hard to read them.

**Comment by Kandroodi** [comment]
The description boxes are adjustable (bottom right corner) and you can adjust them for reading long texts.
BTW, how many rows are convenient as default?

**Comment by josephinevdbent** [comment]
Ah brilliant! Sorry, we didn't notice that. Maybe 4 would be convenient as default?

Thanks!


All best,

Josephine


________________________________
Van: Kandroodi ***@***.***>
Verzonden: woensdag 28 april 2021 15:26
Aan: Kandroodi/WaterSystem
CC: Bent, J.M.C. van den (Josephine); Author
Onderwerp: Re: [Kandroodi/WaterSystem] Please make the box ‘description’ bigger under ‘evidences’ (#81)


The description boxes are adjustable (bottom right corner) and you can adjust them for reading long texts.
BTW, how many rows are convenient as default?

**Comment by Kandroodi** [comment]
It is done.
