### ISSUE TITLE
Double entry in 'Installation List'

### ISSUE THREAD

**Issue by Peter-J-B** [Kandroodi/WaterSystem#90]
I have just made an installation 'Wells at Dirhamīyah-0006', but it is showing up twice in the 'Installation List'. I deleted one of the entries and both were deleted so I made it again and once more there are two entries. Perhaps I am doing something wrong?

Thanks,

Peter

**Comment by Kandroodi** [comment]
Hi Peter,
Did you check this again? Please let me know if there is a problem.
Is it related to issue #93?

**Comment by Peter-J-B** [comment]
Hi Mojtaba,
I just made a new installation and there is only one copy in the installation list so it seems to be working now.
#93 is a different issue.
Thanks for your help!

**Comment by Kandroodi** [comment]
I meant issue #92. 
BTW, it is great that the problem is not there anymore.
