### ISSUE TITLE
multiple entries under 'institution'> 'type'

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#91]
We currently can only enter one 'type' under 'institution', but we would like to have the option of having more than one type per entry (like under 'purpose' under 'installation').

**Comment by Kandroodi** [comment]
Institution type can accept more than one type now. Please notice that the new institution type field is a completely different field than what we had before. So, previously entered data (institution type for two existing entries in institution list) needed to be reinterred again.
