### ISSUE TITLE
entering water system under installation needs to show type as well

### ISSUE THREAD

**Issue by josephinevdbent** [Kandroodi/WaterSystem#93]
some sources use the same term for clearly different types of system. The best example is 'qanat' which comes in both an underground and aqueduct variety. But now, if we want to enter either of those, we can't see which is which. Can the type be added, e.g. between brackets, so we have the options [qanat (qanat)] and [qanat (aqueduct)]?

**Comment by Kandroodi** [comment]
It is done.
